version: "2"
services:
  api:
    build: .
    command: "npm run prod"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production